/**
 * Sitemap & robots.txt generator for my B shoppy (https://mybshoppy.com)
 *
 * Run: npm run sitemap
 * Regenerates public/sitemap.xml and public/robots.txt from the live
 * catalogue (storeConfig).
 */
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { CATEGORIES_CATALOG, INITIAL_PRODUCTS } from '../src/storeConfig';

const SITE_URL = 'https://mybshoppy.com';
const TODAY = new Date().toISOString().split('T')[0];

interface SitemapEntry {
  path: string;
  changefreq: 'daily' | 'weekly' | 'monthly' | 'yearly';
  priority: string;
  lastmod?: string;
}

const entries: SitemapEntry[] = [
  // Core storefront
  { path: '/', changefreq: 'daily', priority: '1.0' },
  { path: '/shop', changefreq: 'daily', priority: '0.9' },
  { path: '/categories', changefreq: 'weekly', priority: '0.9' },

  // Category pages
  ...CATEGORIES_CATALOG.map((category) => ({
    path: `/categories/${category.id}`,
    changefreq: 'weekly' as const,
    priority: '0.8',
  })),

  // Product pages
  ...INITIAL_PRODUCTS.map((product) => ({
    path: `/product/${product.id}`,
    changefreq: 'weekly' as const,
    priority: '0.7',
  })),

  // Content pages
  { path: '/about', changefreq: 'monthly', priority: '0.6' },
  { path: '/contact', changefreq: 'monthly', priority: '0.6' },
];

const escapeXml = (value: string): string =>
  value.replace(/[<>&'"?]/g, (c) => {
    switch (c) {
      case '<':
        return '&lt;';
      case '>':
        return '&gt;';
      case '&':
        return '&amp;';
      case "'":
        return '&apos;';
      case '"':
        return '&quot;';
      case '?':
        return '%3F';
      default:
        return c;
    }
  });

function generateSitemap(): string {
  const urls = entries
    .map(
      (entry) => `  <url>
    <loc>${SITE_URL}${escapeXml(entry.path)}</loc>
    <lastmod>${entry.lastmod || TODAY}</lastmod>
    <changefreq>${entry.changefreq}</changefreq>
    <priority>${entry.priority}</priority>
  </url>`
    )
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.ts - do not edit manually -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

function generateRobots(): string {
  return `# my B shoppy - https://mybshoppy.com
User-agent: *
Allow: /

Sitemap: ${SITE_URL}/sitemap.xml
`;
}

const publicDir = join(process.cwd(), 'public');
mkdirSync(publicDir, { recursive: true });

writeFileSync(join(publicDir, 'sitemap.xml'), generateSitemap(), 'utf8');
writeFileSync(join(publicDir, 'robots.txt'), generateRobots(), 'utf8');

console.log(`[OK] sitemap.xml generated with ${entries.length} URLs`);
console.log(`[OK] robots.txt generated`);
console.log(`     Domain: ${SITE_URL}`);
